// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm115sRY7QdoRnmqUiNZwJvJVH6YMr_Ks',
    appId: '1:260915831579:web:4850dbf3ec11bdd8b829be',
    messagingSenderId: '260915831579',
    projectId: 'algomeal-4ebc5',
    authDomain: 'algomeal-4ebc5.firebaseapp.com',
    storageBucket: 'algomeal-4ebc5.firebasestorage.app',
    measurementId: 'G-5BXQ71BX8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWyK7Wl8gR8d7Bu6pcnF8sd_S1MsaeHQw',
    appId: '1:260915831579:android:64a8350cec3b230ab829be',
    messagingSenderId: '260915831579',
    projectId: 'algomeal-4ebc5',
    storageBucket: 'algomeal-4ebc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ko52ruJdduOUSJyiT5GacjKhqZBVFo0',
    appId: '1:260915831579:ios:2fffc9fc2f88b0fbb829be',
    messagingSenderId: '260915831579',
    projectId: 'algomeal-4ebc5',
    storageBucket: 'algomeal-4ebc5.firebasestorage.app',
    iosBundleId: 'com.example.algoMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ko52ruJdduOUSJyiT5GacjKhqZBVFo0',
    appId: '1:260915831579:ios:2fffc9fc2f88b0fbb829be',
    messagingSenderId: '260915831579',
    projectId: 'algomeal-4ebc5',
    storageBucket: 'algomeal-4ebc5.firebasestorage.app',
    iosBundleId: 'com.example.algoMeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm115sRY7QdoRnmqUiNZwJvJVH6YMr_Ks',
    appId: '1:260915831579:web:01293f7a5445dec4b829be',
    messagingSenderId: '260915831579',
    projectId: 'algomeal-4ebc5',
    authDomain: 'algomeal-4ebc5.firebaseapp.com',
    storageBucket: 'algomeal-4ebc5.firebasestorage.app',
    measurementId: 'G-K40QL6SY9J',
  );
}
